name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      clear-cache:
        description: "Clear the ./cache folder before the build"
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Restore Cache (node_modules and .astro)
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./.astro
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: cache/
          key: ${{ runner.os }}-content-${{ hashFiles('cache/**/*') }}
          restore-keys: |
            ${{ runner.os }}-content-

      - name: Conditionally Clear ./cache
        if: ${{ inputs.clear-cache == 'true' }}
        run: rm -rf ./cache

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVILEGED_GITHUB_TOKEN }}
